In [20]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.4.22)

In [21]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ammaraahmad/us-ecommerce-record-2020")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'us-ecommerce-record-2020' dataset.
Path to dataset files: /kaggle/input/us-ecommerce-record-2020

In [22]:
import os

print(os.listdir(path))

['US  E-commerce records 2020.csv']

In [23]:
import pandas as pd
import os

In [24]:
file_path = os.path.join(path, "US  E-commerce records 2020.csv")

df = pd.read_csv(file_path, encoding='latin-1')

In [25]:
df. head(3
         )

,Order Date,Row ID,Order ID,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,01-01-20,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,East,FUR-FU-10003878,Furniture,Furnishings,"Linden 10"" Round Wall Clock, Black",48.896,4,0.2,8.5568
1,01-01-20,4010,CA-2017-144463,Standard Class,SC-20725,Consumer,United States,Los Angeles,California,90036,West,FUR-FU-10001215,Furniture,Furnishings,"Howard Miller 11-1/2"" Diameter Brentwood Wall ...",474.430,11,0.0,199.2606
2,01-01-20,6683,CA-2017-154466,First Class,DP-13390,Home Office,United States,Franklin,Wisconsin,53132,Central,OFF-BI-10002012,Office Supplies,Binders,Wilson Jones Easy Flow II Sheet Lifters,3.600,2,0.0,1.7280

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3312 non-null   object
 1   Row ID        3312 non-null   int64
 2   Order ID      3312 non-null   object
 3   Ship Mode     3312 non-null   object
 4   Customer ID   3312 non-null   object
 5   Segment       3312 non-null   object
 6   Country       3312 non-null   object
 7   City          3312 non-null   object
 8   State         3312 non-null   object
 9   Postal Code   3312 non-null   int64
 10  Region        3312 non-null   object
 11  Product ID    3312 non-null   object
 12  Category      3312 non-null   object
 13  Sub-Category  3312 non-null   object
 14  Product Name  3312 non-null   object
 15  Sales         3312 non-null   float64
 16  Quantity      3312 non-null   int64
 17  Discount      3312 non-null   float64
 18  Profit        3312 non-null   float64
dtypes: float64(3), int64(3), object(13)
memory usage: 491.8+ KB

In [27]:
df.shape

(3312, 19)

In [28]:
df.columns

Index(['Order Date', 'Row ID', 'Order ID', 'Ship Mode', 'Customer ID',
       'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales',
       'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [29]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [30]:
df.head(1)

,order_date,row_id,order_id,ship_mode,customer_id,segment,country,city,state,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,01-01-20,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,East,FUR-FU-10003878,Furniture,Furnishings,"Linden 10"" Round Wall Clock, Black",48.896,4,0.2,8.5568

In [31]:
#df.isnull().sum()

(df.isnull().sum() / len(df)) * 100

order_date      0.0
row_id          0.0
order_id        0.0
ship_mode       0.0
customer_id     0.0
segment         0.0
country         0.0
city            0.0
state           0.0
postal_code     0.0
region          0.0
product_id      0.0
category        0.0
sub-category    0.0
product_name    0.0
sales           0.0
quantity        0.0
discount        0.0
profit          0.0
dtype: float64

In [32]:
df['order_date'] = pd.to_datetime(df['order_date'])

/tmp/ipykernel_497/2765250300.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['order_date'] = pd.to_datetime(df['order_date'])

In [33]:
df['ship_mode'] = df['ship_mode'].astype('category')

In [34]:
df['segment'] = df['segment'].astype('category')

In [35]:
df['region'] = df['region'].astype('category')
df['category'] = df['category'].astype('category')

In [36]:
df.columns = df.columns.str.replace('-', '_')

In [37]:
df['sub_category'] = df['sub_category'].astype('category')

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df['profit_margin'] = df['profit'] / df['sales']

In [40]:
df['is_loss'] = df['profit'] < 0

In [41]:
df['order_month'] = df['order_date'].dt.month

In [42]:
df['sales_per_unit'] = df['sales'] / df['quantity']

In [43]:
df.head(3)

,order_date,row_id,order_id,ship_mode,customer_id,segment,country,city,state,postal_code,...,sub_category,product_name,sales,quantity,discount,profit,profit_margin,is_loss,order_month,sales_per_unit
0,2020-01-01,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,...,Furnishings,"Linden 10"" Round Wall Clock, Black",48.896,4,0.2,8.5568,0.175,False,1,12.224
1,2020-01-01,4010,CA-2017-144463,Standard Class,SC-20725,Consumer,United States,Los Angeles,California,90036,...,Furnishings,"Howard Miller 11-1/2"" Diameter Brentwood Wall ...",474.430,11,0.0,199.2606,0.420,False,1,43.130
2,2020-01-01,6683,CA-2017-154466,First Class,DP-13390,Home Office,United States,Franklin,Wisconsin,53132,...,Binders,Wilson Jones Easy Flow II Sheet Lifters,3.600,2,0.0,1.7280,0.480,False,1,1.800

In [44]:
import os

os.makedirs("data/cleaned", exist_ok=True)

In [45]:
df.to_csv("data/cleaned/ecommerce_cleaned.csv", index=False)

In [46]:
df.head(3)

,order_date,row_id,order_id,ship_mode,customer_id,segment,country,city,state,postal_code,...,sub_category,product_name,sales,quantity,discount,profit,profit_margin,is_loss,order_month,sales_per_unit
0,2020-01-01,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,...,Furnishings,"Linden 10"" Round Wall Clock, Black",48.896,4,0.2,8.5568,0.175,False,1,12.224
1,2020-01-01,4010,CA-2017-144463,Standard Class,SC-20725,Consumer,United States,Los Angeles,California,90036,...,Furnishings,"Howard Miller 11-1/2"" Diameter Brentwood Wall ...",474.430,11,0.0,199.2606,0.420,False,1,43.130
2,2020-01-01,6683,CA-2017-154466,First Class,DP-13390,Home Office,United States,Franklin,Wisconsin,53132,...,Binders,Wilson Jones Easy Flow II Sheet Lifters,3.600,2,0.0,1.7280,0.480,False,1,1.800

In [47]:
from google.colab import files
files.download("data/cleaned/ecommerce_cleaned.csv")